### PR TITLE
added instruction to convert while capturing

### PR DESCRIPTION
**Pull request by OliverLonghi**

### CODE REVIEW

**Comment by stephenlacy** [comment]
Thanks, can you add comments relating to deleting/creating the `.audio` and `.video` folders?

**Comment by OliverLonghi** [comment]
.audio will storage the raw audio
.video will storage the converted video
and video.avi will save to disk a video with audio and video

**Comment by stephenlacy** [comment]
did you mean to close this issue, or should I merge?

**Comment by OliverLonghi** [comment]
sorry, I miss clicked the button. It is up to you to merge or not. 
The original example is not working to me. So I did that new one, that actually is not exactly why I need. I would like convert both raw video and audio to video.avi but I could only make it in two steps.

**Pull request closed without merging**
